"""message

Revision ID: 132b1e833865
Revises: 0241054e3cd0
Create Date: 2024-07-24 15:32:40.046280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132b1e833865'
down_revision = '0241054e3cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
